### PR TITLE
added all the frame work for the HTML and CSS needed to start. Will p…

### PR DESCRIPTION
**Pull request by aww2539**
# Description

Added all the frame work for the HTML and CSS needed to start. Will probably require some changes later on, but it is a good starting point.

### CODE REVIEW

**Comment by aww2539** [comment]
Tried to get the CSS to resemble the wire diagram in the instructions because I was bored. Let me know if there is anything you would change about it.

**Comment by jmrosenberger** [comment]
looks good

**Review by travish-io — APPROVED** [review]
👍

**Review by jmrosenberger — APPROVED** [review]
good

**Pull request merged**
